# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example7' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Starscream', '~> 3.0.2'

  # Pods for Example7

end
